title: Mehmet Aydın
email: m3hmetaydn@gmail.com
description: Kişisel blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m3hm3taydin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: m3hm3taydin
github_username:  m3hm3taydin

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - etiketler.html
  - arsiv.html
  - hakkimda.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
